### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by joeldavidson1** [v-Zak/CMP1903M-Assessment-1#3]
### Is the code properly documented/commented?
The code is commented very well, with every line either being self-explained from excellent use of variable naming or from comments. I have struggled to find any methods or lines that either are not commented well or are self-explanatory.

The following are just nitpicky typos that could make it look even more professional for other people reading the code:
Input.cs 
Line 25 – Returning has a typo.
Line 107 – Character has a typo.
Line 126 – Unexpected has a typo.

Analyse.cs
Line 39, 161, 164, 165, 168, 178, 181, 182, 189, 204 – Occurrences has a typo.
Line 208 – Whether has a typo.

Report.cs
Line 39 – Frequency has a typo.

### Does the code handle errors properly?
Extensive use of error handling is demonstrated and used appropriately, and any errors that are thrown loop back into the program to allow the user to continue. Errors that are raised display a message which tells the user why they are receiving an error which is helpful. 

Although it doesn’t affect the program, the only error I can find is when the user enters an empty string in option 2 for a file path. The program says a test file will be used, but it says the file can’t be found if it isn't present in that specific directory. This is still handled well, though, as it asks the user to re-enter a file path.

### What suggestions do you have to improve the code?
Overall, the project works excellently and achieves all the correct criteria for a high-level grade. Text is analysed correctly with both keyboard and file input. I have struggled to find many changes that I would make or any errors that are not handled correctly.

To improve, the FrequencyPair.cs seems unnecessary as its own class as this could be incorporated into the Analyse.cs class to better stick to the OOP principles of bunching related data and objects together (FrequencyPair.cs is essentially another Analyse method). Also, in the FrequencyPair.cs class, the variables can be accessed and changed elsewhere within the program, e.g. in Analyse.cs, a value or frequency could be added using pair.value = or pair.frequency =, which would alter the analysis of the text. This could be easily improved by encapsulating both the variables and perhaps having them publicly accessible but privately set so they could not be changed manually elsewhere.

One final nitpicky point (as I’m struggling to find many nitpicks or errors at all) which will not matter whatsoever in the running of the program is on line 89 of Input.cs - path == null || path == “” could be changed to a built-in C# method - String.IsNullOrEmpty.

**Comment by v-Zak** [comment]
Perfect, I'll think about the changes specified and incorporate them into the code and close the issue.
