### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by xBrooky** [v-Zak/CMP1903M-Assessment-1#5]
Code Review

1. is the code properly documented/commented?
The code is formatted clearly and easy to follow for anyone reading or reviewing it. The choice of naming conventions means it is simple to understand what goes where and how the functions are being utilised. The comments provided are relevant to the code below and don’t contain too much information but enough to make it clear what the specific function is doing by correctly outline the input and output methods of the code.

2. Does the code handle errors properly?
Input errors for the code are handled very well, upon typing an incorrect option number or even a letter, a custom error message is displayed stating to the user that “  _ is not valid. Try Again”. This is then followed by presenting the user with the same choice of options again in order to ensure that a valid option is chosen. 

The use of recursively calling the function and the implementation of “try” and “catch”, further ensures that the user will be given multiple opportunities to type a correct input and crash the program by using an input that is not linked to anything in the program.

In line 125 of “Input.cs”, a FileNotFoundException is used which is thrown when an attempt to access a file that does not exist on the disk. Like before if typing an incorrect path occurs then the user is presented with the same choice again to enter a valid path. A feature that was included for the user if they didn’t want to type a path was to simply press “Enter” and this would run the test file.

Overall, I would say there is a good use of error handling within this code, errors that have been made are presented in a clear manor to the end user. Importantly upon incorrect information being entered the program does not seem to crash or break in anyway and keep presenting the user with a choice until a valid input has been made.

3. Suggestions for improvement:
The main suggestion for improvement I could make would be the implementation of a “test class”. What this “test class” would do is run a test file and compare it with expected results. This would just be a good way to ensure that the code is running efficiently and effectively and checking all of the boxes that it needs to.

4. Any nit-picks? 
The previous issue raised mentioned the only nit-picks to be a few typo mistakes in the code. After inspecting the code, myself I can agree that these were the only minor errors in the code;
Input.cs: Line 25, Line 107, Line 126 – typo.
Analyse.cs: Line 39, 161, 164, 165, 168, 178, 181, 182, 189, 204, 208- typo.
Report.cs: Line 39 –typo.

Since reviewing however, these mistakes have been corrected so I believe that there are now NO more nit-pick errors in the code

5. Summary:
Overall, a very good, polished program with only a few tiny errors. I believe you have followed the given brief very effectively and created a program that focuses on efficiency and does not repeat unnecessary information in a way that would make the code messy and unreadable. 

From my point of view after reading and reviewing the code there is not really anything major I feel would need to change to make this code more optimal.

**Comment by v-Zak** [comment]
Thanks Callum, I will make sure to have a look at adding a test class.
